- name: CREATE DEVOPS ASSETS and ENVIRONMENT
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:

## From - https://medium.com/@itsdavidthai/comprehensive-aws-ec2-deployment-with-travisci-guide-7cafa9c754fc
### Storage resources for build assets
    - name: Create Repository Storage bucket - Release path, in region
      aws_s3:
        bucket: "{{ domain_name }}.repository"
        mode: create
        region: "{{ aws_region }}"

    - name: Create Repository Storage bucket - Snapshot path, in region
      aws_s3:
         bucket: "{{ domain_name }}.snapshot"
         mode: create
         region: "{{ aws_region }}"

#    - name: Create buildusers group
#      iam_group:
#        name: buildusers
#        state: present

### Build Group
  ##  - name: Create buildusers group
  ##    iam_group:
  ##      name: buildusers
  ##      state: present


### Add Policies to builduser group
#    - name: Assign a policy for artifact deploys to the buildusers group
#      iam_policy:
#        iam_type: group
#        iam_name: buildusers
#        policy_name: build-deployment
#        state: present
#        policy_document: files/buildrole-deploy-artifact.json

    - name: Assign a policy for pushing built artifacts to repos for the buildusers group
      iam_policy:
        iam_type: group
        iam_name: buildusers
        policy_name: build-push-to-repo
        state: present
        policy_document: files/buildrole-push-to-repo.json

### Create an EC2 role with policy to access Repo asset

    - name: Create EC2 Role for retrieving archives
      iam:
        iam_type: role
        name: ec2-readrepo-role
        state: present

    - name: Assign policy for retrieving repo assets to EC2 role
      iam_policy:
         iam_type: role
         iam_name: ec2-readrepo-role
         policy_name: ec2-getrepodata-policy
         policy_document: files/ec2-getrepodata-policy.json
         state: present


### Build user - assign to Group
    - name: Create a new IAM builduser with API keys
      iam:
         iam_type: user
         name: "builduser"
         state: present
         password: "P3rs3ph0ne!"
         access_key_state: create
         groups: buildusers
      register: builduser

### CodeDeploy application



### Policy for Server
## Should have created 2 new S3 resources
## arn:aws:s3:::snapshot
## arn:aws:s3:::repository
