---
# AWS tasks are run 'locally'

# Authentication details should be passed in as arguments or exported in the shell before running this playbook
# Ideally they should be stored in Hashicorp's 'Vault'
# e.g.
# export AWS_ACCESS_KEY_ID='my-access-key123'
# export AWS_SECRET_ACCESS_KEY='sekrit23418'
#
# Run with `ansible-playbook -i testing infra.yml`

## Create a VPC - non default
- name: CREATE AWS ENVIRONMENT
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Find VPC
      ec2_vpc_net_facts:
          region: "{{ aws_region }}"
          filters:
            "tag:Name": vpc-{{ domain_name }}
      register: vpc_facts

    - name: Find NAT GATEWAY
      ec2_vpc_nat_gateway_facts:
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_facts.vpcs[0].id}}"
      register: all_ngws


    - name: Delete NAT Gateway
      ec2_vpc_nat_gateway:
        state: absent
        region: "{{ aws_region }}"
        wait: yes
        nat_gateway_id: "{{ item.NatGatewayId }}"
        release_eip: yes
      register: delete_nat_gateway_result
      with_items: "{{ all_ngws.results }}"

    - name: Find Elastic IPv4 address

    - name: Delete Elastic IPv4 address

    - name: Delete VPC and all resources
      ec2_vpc_net:
        state: absent
        region: "{{ aws_region }}"
        purge_cidrs: yes
        name: vpc-{{ domain_name }}
