---
# AWS tasks are run 'locally'

# Authentication details should be passed in as arguments or exported in the shell before running this playbook
# Ideally they should be stored in Hashicorp's 'Vault'
# e.g.
# export AWS_ACCESS_KEY_ID='my-access-key123'
# export AWS_SECRET_ACCESS_KEY='sekrit23418'
#
# Run with `ansible-playbook -i testing infra.yml`
- name: CREATE AWS ENVIRONMENT
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # t3 has enhanced networking
    instance_type: t3.nano

# EXERCISE 10.1 - 10.7 of AWS Advanced Networking
# Create cloudFormation using templates
  tasks:
  - name: Create CloudFormation stack
    cloudformation:
      stack_name: "NetAutomation"
      state: "present"
      region: "{{ aws_region }}"
      disable_rollback: true
      template: "cloudformation/vpc.yml"
      tags:
        Stack: "ansible-cloudformation"


  - name: Update CloudFormation stack
    cloudformation:
      stack_name: "NetAutomation"
      state: "present"
      region: "{{ aws_region }}"
      disable_rollback: true
      template: "cloudformation/vpc_10_2.yml"
      template_parameters:
        AZ: "{{ aws_region }}a"
        VPCCIDRRange: "10.1.0.0/16"
        SubnetCIDRRange: "10.1.0.0/24"
      tags:
        Stack: "ansible-cloudformation"

  - name: Update with error in CloudFormation stack
    cloudformation:
      stack_name: "NetAutomation"
      state: "present"
      region: "{{ aws_region }}"
      disable_rollback: true
      template: "cloudformation/vpc_10_2.yml"
      template_parameters:
        AZ: "{{ aws_region }}a"
        VPCCIDRRange: "10.1.0.0/16"
        SubnetCIDRRange: "10.2.0.0/24"
      tags:
        Stack: "ansible-cloudformation"
