---
# AWS tasks are run 'locally'

# Authentication details should be passed in as arguments or exported in the shell before running this playbook
# Ideally they should be stored in Hashicorp's 'Vault'
# e.g.
# export AWS_ACCESS_KEY_ID='my-access-key123'
# export AWS_SECRET_ACCESS_KEY='sekrit23418'
#
# Run with `ansible-playbook -i testing infra.yml`

## Create a VPC - non default
- name: CREATE AWS ENVIRONMENT
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    instance_type: t2.nano
    ec2_count: 1
    #pwd_alias: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
    pwd_alias: "6VZyhMdvsuQR3CNyj8dZ70WEPFedlTKq"
# This playbook sets up an Amazon VPN environment
  tasks:
  - name: create a new ec2 key pair 'vpn_keypair', returns generated private key
    ec2_key:
      name: vpn_keypair
      region: "{{ aws_region }}"
      force: false
    register: vpn_key_result

  - name: Save private vpn key in a local safe space
    copy: content="{{ vpn_key_result.key.private_key }}" dest="./aws.vpn.{{ domain_name }}.pem" mode=0400
    when: vpn_key_result.changed


  - name: Generate an OpenSSL Private Key IPSEC Pre-Shared Key
    debug:
      msg: "Pre-shared key is {{ pwd_alias }}"

  # Gather facts about any VPC with a tag key Name and value Example
  - name: Get matching VPC
    ec2_vpc_net_facts:
      region: "{{ aws_region }}"
      filters:
        "tag:domain_name": "{{ domain_name }}"
    register: avpc

  - name: Set VPC ID in variable
    set_fact:
       vpc_id: "{{ avpc.vpcs[0].vpc_id }}"

  - name: Pre-check if Flow logs exist?
    local_action: shell aws ec2 describe-flow-logs --filter "Name=log-group-name,Values=vpc-{{ domain_name }}"
    register: flow_logs_list

  - name: Create Cloudwatch log group
    cloudwatchlogs_log_group:
      state: present
      log_group_name: "vpc-{{ domain_name }}"
      tags: { "domain": "{{ domain_name }}", "scope" : "VPC" }
    when: not flow_logs_list.stdout | regex_search('CreationTime')
    register: clw_group

  - name: Find Role info for AWSServiceRoleForVPCS2SVPN
    iam_role_info:
      name: AWSServiceRoleForVPCS2SVPN
    register: iam_role




  - name: enable vpc flow logs write as Role AWSServiceRoleForVPCS2SVPN
    local_action: shell aws ec2 create-flow-logs --resource-type VPC --traffic-type ALL --resource-ids {{ vpc_id }} --traffic-type ALL --log-group-name vpc-{{ domain_name }} --deliver-logs-permission-arn {{ iam_role.iam_roles[0].arn }}
    when: not flow_logs_list.stdout | regex_search('CreationTime')

  - name: Find my public ip
    uri:
      url: http://ifconfig.me/ip
      return_content: yes
    register: ip_response




  # Get VPC SubnetId's
  - name: Get Public Subnet list
    ec2_vpc_subnet_facts:
      filters:
        vpc-id: "{{ vpc_id }}"
        "tag:zone":  "public"
    register: subnet_facts

  - name: Create subnet id's list variable
    set_fact:
      subnet_ids: "{{ subnet_facts.subnets|map(attribute='id')|list }}"

  - name: Create VPN Security Group
    ec2_group:
      name: vpn-ipsec-secgroup
      description: VPN Security Group
      vpc_id: "{{ vpc_id }}"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ ip_response.content }}/32"
      - proto: udp
        from_port: 4500
        to_port: 4500
        cidr_ip: "{{ ip_response.content }}/32"
      - proto: udp
        from_port: 500
        to_port: 500
        cidr_ip: "{{ ip_response.content }}/32"


  # Ecs / EC2 Container instance
  # AMI ID: ami-02a2ea2b210628cc5
  # t2.micro size
  # Number of instances
  ## Spot + OnDemand (1-2)?
  ##  Auto assign public IP
  ## Role: ecsInstanceRole
  ## SecGroup: ecs_secgroup
  ## Volume: 30GB
  ## Subnet(s)
  - name: Launch ECS AMI EC2 instance in public subnet 1a
    ec2:
      group: vpn-ipsec-secgroup
      instance_type: "{{ instance_type }}"
      ##  Canonical, Ubuntu, 16.04 LTS, amd64 xenial image build on 2018-05-22
      image: ami-07cd0d3b7336a9564
      vpc_subnet_id: "{{ subnet_ids[0] }}"
      assign_public_ip: yes
      wait: true
      region: "{{ aws_region }}"
      keypair: "vpn_keypair"
      count_tag:
        type: vpn
      exact_count: 2
      # mkdir -p /run/pluto /var/run/pluto /var/run/xl2tpd\nrm -f /run/pluto/pluto.pid /var/run/pluto/pluto.pid /var/run/xl2tpd.pid\n/usr/local/sbin/ipsec start\nexec /usr/sbin/xl2tpd -D -c /etc/xl2tpd/xl2tpd.conf
      user_data: "#!/bin/bash \n/opt/src/run.sh"
      instance_tags:
        type: vpn
        description: eu-west-1 Amazon ECS-optimized Amazon Linux 2
    register: ec2_vpn_instance_1a

  - name: Launch ECS AMI EC2 instance in public subnet 1c
    ec2:
      group: vpn-ipsec-secgroup
      instance_type: "{{ instance_type }}"
      ##  Debian Gnu Linux 9 Stretch with Libreswan VPN
      image: ami-07cd0d3b7336a9564
      vpc_subnet_id: "{{ subnet_ids[1] }}"
      assign_public_ip: yes
      wait: true
      region: "{{ aws_region }}"
      keypair: "vpn_keypair"
      count_tag:
        type: vpn
      exact_count: 2
      user_data: "#!/bin/bash \n/opt/src/run.sh"
      instance_tags:
        type: vpn
        description: eu-west-1 Amazon ECS-optimized Amazon Linux 2
    register: ec2_vpn_instance_1c

  # Create AWS to Client VPN connection
  - name: Create a new Virtual Private Gateway attached to our VPC
    ec2_vpc_vgw:
      state: present
      region: "{{ aws_region }}"
      vpc_id: "{{ vpc_id }}"
      name: "vpc-vgw-{{ domain_name }}"
      type: ipsec.1
    register: created_vgw

  - name: Create customer gateway using IP - Account level
    ec2_customer_gateway:
      ip_address: "{{ ip_response.content }}"
      name: NeilHome
      routing: static
      bgp_asn: 65000
      region: "{{ aws_region }}"
      state: present
    register: customer_gw


  - name: create a VPN connection
    ec2_vpc_vpn:
      state: present
      vpn_gateway_id: "{{ created_vgw.vgw.id }}"
      customer_gateway_id: "{{ customer_gw.gateway.customer_gateways[0].customer_gateway_id }}"
      static_only: yes
      tunnel_options:
       -
        PreSharedKey: "{{ pwd_alias }}"
       -
        PreSharedKey: "{{ pwd_alias }}"
      routes:
        - 92.238.125.122/32
        - 192.168.0.0/24
    register: vpn_conn

  # Configure our Local VPN Server - IPSec
  # options.tunnel_options[X].outside_ip_address
  # options.tunnel_options[X].pre_shared_key
  # vpc_id.vpc[0].cidr_block

  # Search replace Outside IP Address, VPC CIDR and Pre-Shared key in conf, secrets filters

  - name: Write an ENV file for the VPN Gateway
    copy: content="VPN_IPSEC_PSK={{ pwd_alias }}\nVPN_USER=vpnuser\nVPN_PASSWORD=vpnpass\nAWS_TUNNEL1_IP={{ vpn_conn.options.tunnel_options[0].outside_ip_address }}\nAWS_TUNNEL2_IP={{ vpn_conn.options.tunnel_options[1].outside_ip_address }}\nAWS_CIDR={{ avpc.vpcs[0].cidr_block }}\nLOCAL_CIDR=192.168.0.0/24" dest=./vpn.env

  # Run a docker container npiper/docker-ipsec-vpn-server configured with AWS connections
  # docker run -d -p 500:500/udp -p 4500:4500/udp -p 1701:1701/udp -e VPN_USER=vpnuser -e VPN_PASSWORD=vpnpass --privileged -v`pwd`/config:/etc/ipsec.d philplckthun/strongswan
  #- name: Start a container and use an env file
  #  docker_container:
  #    name: docker-ipsec-vpn-server
  #    image: npiper/docker-ipsec-vpn-server
  #    env_file: ./vpn.env
  #    state: started
  #    exposed_ports:
  #      - 500
  #      - 4500
  #      - 1701
  #    restart: yes
  #    privileged: yes
  #    detach: yes
